main:
  field_code_state:
  field_t_outdoor:
  field_t_channel:
  field_t_water:
  field_perf_water_cal:
  control:
    label: Управление
control:
  field_code_state:
  but_start:
  but_stop:
  stat_winter_summer:
  stat_remote_local:
  field_code_alarm:
  but_alarm_reset:
  field_set_t:
  set_t:
    minValue: 15
    maxValue: 30
    step: 0.5